### ISSUE TITLE
Cannot blur 'Baidu MapView' and 'SurfaceView'

### ISSUE THREAD

**Issue by imknown** [mmin18/RealtimeBlurView#10]
I've read the urls below:
> http://stackoverflow.com/questions/24317041/google-maps-with-blur-layer
> https://github.com/flurgle/BlurKit-Android#to-do-incoming

Any way to do that? :[

![screenshot_2017-03-02-16-36-47-53](https://cloud.githubusercontent.com/assets/5681447/23499454/24fb430c-ff67-11e6-9ed0-33e84100e1a7.png)

**Comment by Dimezis** [comment]
No, you can't blur SurfaceView

**Comment by mmin18** [comment]
Sorry SurfaceView / TextureView is not supported.
