### ISSUE TITLE
TextureView blur

### ISSUE THREAD

**Issue by TooLazyy** [mmin18/RealtimeBlurView#17]
Why TextureView or SurfaceView are not supported?

**Comment by tangxianqiang** [comment]
@TooLazyy Because you can't get a bitmap from opengl view easily

**Comment by tangxianqiang** [comment]
@TooLazyy It always need a bitmap to blur,however  you can't get a bitmap from opengl view easily

**Comment by mmin18** [comment]
It draws on different canvas and different threads. So the implementation could be complicated and buggy.
