### ISSUE TITLE
Crashes with App converted to AndroidX on older versions of Android

### ISSUE THREAD

**Issue by znerol** [mmin18/RealtimeBlurView#28]
After converting an App to AndroidX it started to crash on Android 5 devices. Regrettably there is no traceback since this happens in the native part. However, the crashes stopped after I removed RealtimeBlurView from the app.

```
W/linker: librsjni_androidx.so: unused DT entry: type 0x6000000f arg 0xaf80
    librsjni_androidx.so: unused DT entry: type 0x60000010 arg 0x1d
    librsjni_androidx.so: unused DT entry: type 0x6ffffef5 arg 0xad5c
    librsjni_androidx.so: unused DT entry: type 0x6ffffffe arg 0xad1c
    librsjni_androidx.so: unused DT entry: type 0x6fffffff arg 0x2

    --------- beginning of crash
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3862 (app.id.here)
```

In this particular case it would be possible to just use vanilla RenderScript instead of the one in support library. Others suggest this solution [as well](https://stackoverflow.com/questions/52781821/renderscript-broken-with-androidx).

Thus it would be great if this library would come in multiple flavors _vanilla_, _supportlib_ and maybe _androidx_ as well in the future.

**Comment by SamYStudiO** [comment]
Hi,
same pb here after migrating to andoidx

**Comment by mmin18** [comment]
Resolved in v1.2

**Comment by WinterHuang003** [comment]
@mmin18 How to resolve?replace "androidx.renderscript.*" by "android.renderscript.*"?

**Comment by mmin18** [comment]
Do you still have the same issue after v1.2?

**Comment by WinterHuang003** [comment]
> Do you still have the same issue after v1.2?

no.   I just want to know that  you have other resolutions or not
