### ISSUE TITLE
Not support PopupWindow!

### ISSUE THREAD

**Issue by KennethLaw** [mmin18/RealtimeBlurView#5]
Work fine on Activity but not work on popupWindow

**Comment by mmin18** [comment]
Fixed in v1.0.5, can you verify.
`    dependencies {
        compile 'com.github.mmin18:realtimeblurview:1.0.4'
    }
`

**Comment by KennethLaw** [comment]
My sample app is using WindowManager where were added a RealtimeBlurView，Or can not work normally.
