### ISSUE TITLE
Any public method to pause blur when activity is paused?

### ISSUE THREAD

**Issue by imknown** [mmin18/RealtimeBlurView#8]
> https://github.com/mmin18/RealtimeBlurView/blob/master/library/src/com/github/mmin18/widget/RealtimeBlurView.java#L121

Is it?

**Comment by mmin18** [comment]
No. And it don't has a pause method.

The blur will only trigger when activity draws, and background activity will not draw (unless the active activity is transparent)

**Comment by imknown** [comment]
Thx, i created one `ViewStub` for `BlurView` on my root `Activity` (the `Activity` has fragments).
When i call `BlurView.setVisibility(View.GONE)`, and will it a good way to hide the `BlurView`?

**Comment by mmin18** [comment]
Yes. If it's hidden, it will not blur.

**Comment by imknown** [comment]
Thank you a lot.
